export {
  ISTANBUL,
  MECCA,
  LONDON,
  ISTANBUL_SUMMER_AFTERNOON,
  ISTANBUL_SUMMER_NIGHT,
  ISTANBUL_WINTER_MORNING,
  MECCA_RAMADAN_EVENING,
  MECCA_RAMADAN_PRE_FAJR,
  LONDON_SPRING_NOON,
  ALL_FIXTURES,
} from './fixtures.js';
